### PR TITLE
Add basic tools to Dockerfile

### PR DESCRIPTION
**Pull request by gaby**
* Added bind-tools (BIND9) to help DNS performance within Docker Networks/Kubernetes.
* Added ca-certificates for common certificates when using HTTPS/TLS
* Temporarily added the `shadow` package to create a user/group for glider. 
* Pinned build image to golang 1.16 instead of latest.
* Glider will now run as `glider` user and the `/app` is now owned by glider.

### CODE REVIEW

**Comment by gaby** [comment]
@nadoo Let me know your thoughts on this. We are using a similar setup for our images and it has been working great with HTTP, SOCKS5 and TCP proxies.

**Comment by nadoo** [comment]
Hi @gaby , thanks for your PR!

**Comment by gaby** [comment]
@nadoo i just noticed that line 19 is missing a backslash!

**Comment by nadoo** [comment]
Hi @gaby , glider v0.16.0 will be released when Go1.18 is out(soon), and the docker image will keep simple and small so the bind-tools will not be installed anymore. You can use glider image as a base image and create your own. 
The dev tag(`nadoo/glider:dev`) has already been changed, you can check it if you need.

Thanks for your help to make glider better, and I'm sorry for the inconvenience here.

**Comment by gaby** [comment]
@nadoo No worries, it should still work for us. :-) Thanks for letting me know! Looking forward to v0.16.0

**Pull request merged**
