### PR TITLE
Add Dockerfile

### PR DESCRIPTION
**Pull request by rustycl0ck**
Addresses #65

### CODE REVIEW

**Comment by nadoo** [comment]
Thanks! there was an PR #185 about Dockerfile and it has been merged, any updates here?

**Comment by rustycl0ck** [comment]
> Thanks! there was an PR #185 about Dockerfile and it has been merged, any updates here?

No, sorry, this is the same! (Maybe the fork was never rebased with the upstream, so it is still showing the diff).

But I don't see any  images at https://hub.docker.com/r/nadoo/glider.
Would be great if you can point to the docker image in location in the `README.md`.

**Comment by nadoo** [comment]
Yes, cuz I don't use docker, so I haven't add any scripts to generate docker image on docker hub, any PR is welcomed.

**Comment by nadoo** [comment]
I've added a script to upload docker image automatically, and I'll release a version soon:
https://hub.docker.com/r/nadoo/glider/tags

**Comment by rustycl0ck** [comment]
Sorry for the late reply, but you actually don't need any script for that. You just need to enable the `auto` builds on docker hub so that whenever you push any tags to the github repo, dockerhub will automatically build the image and apply the same tag to the image as well. - https://docs.docker.com/docker-hub/builds/link-source/

**Comment by rustycl0ck** [comment]
I don't recall exactly, but I think you will probably need to delete the `nadoo/glider` dockerhub repo and create it again with the automatic builds enabled. I don't think there is an option to enable automatic builds for any existing repos, it is just available at the time of repo creation.

**Comment by nadoo** [comment]
Hi @rustycl0ck , thank you very much for your help, I'm following the Github's instruction to publish docker images and it worked without problem:
https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images

**Comment by rustycl0ck** [comment]
This is perfect! Thanks @nadoo :+1:

**Pull request closed without merging**
