### PR TITLE
When checkinterval is set to 0, disable periodical proxy checking and set all proxies to enabled

### PR DESCRIPTION
**Pull request by aeroxy**

### CODE REVIEW

**Comment by xlighting2017** [comment]
it's not a good idea to presume every fwder is working by deafult, 
it was set to disabled on purpose...see #81 for more details :)
hint: if you do so, and your first fwder happen to be broken, you will get a dead loop

**Comment by aeroxy** [comment]
Sure I am aware of the potential problem, but assuming someone set the checkinterval to 0, this usually means he or she doesn't want to check the proxies at all whatsoever. In my case I do not care about the latency or availability of my proxies I can be confident that they are all available and have minimal latency.

**Comment by nadoo** [comment]
[glider-v0.10.0-linux-x86_64.zip](https://github.com/nadoo/glider/files/4567691/glider-v0.10.0-linux-x86_64.zip)

now we have a new option `checkdisabledonly` to let glider check disabled forwarders only, if it is set to `true`, glider will check all forwarders at startup and will never check them again if they're always available.

you can check the attachment to see whether it meets your requirements.

**Comment by nadoo** [comment]
Closed due to new version released.

**Pull request closed without merging**
