### PR TITLE
fix(vmess): panic caused by length exceeded

### PR DESCRIPTION
**Pull request by mzz2017**
This should fix https://github.com/nadoo/glider/issues/301.

### CODE REVIEW

**Comment by nadoo** [comment]
Thank you very very much! I haven't modify the vmess codes for a long time so I'm not familiar with it now, thanks for your kindly help!

Can you please also take a look at the chunk reader & writer? when I set the security to `none`, like: `-forward vmess://none:UUID@server:port`, it also panics.

**Comment by mzz2017** [comment]
Fixed. Sorry for my mistake.

**Comment by nadoo** [comment]
Thanks!

**Comment by nadoo** [comment]
Hi @mzz2017 , I spent some time to look into v2ray's code(it's too huge and complicate and hard to read) and I found that the server will always send data by spliting it shorter than 2048:

https://github.com/v2fly/v2ray-core/blob/054e6679830885c94cc37d27ab2aa96b5b37e019/common/crypto/auth.go#L281-L308

```Go
payloadSize := buf.Size - int32(w.auth.Overhead()) - w.sizeParser.SizeBytes() - maxPadding
```
and the buf.Size is a const:
https://github.com/v2fly/v2ray-core/blob/054e6679830885c94cc37d27ab2aa96b5b37e019/common/buf/buffer.go#L9-L12
```Go
const (
	// Size of a regular buffer.
	Size = 2048
)
```

I dunno why the ShakeSizeParser sometimes returned a `size` larger than 16384, it's weird, and when the size is larger than 2048, it always failed to read data and we will get an EOF error.

So I'll simply add a size check based on the code from v0.15.1, thanks for you help!

**Comment by mzz2017** [comment]
@nadoo  I noticed that. But after this PR #302, all size is small than 2048 and no any one will exceed.
I simply checked the code and do not know why. Nevertheless, it works.

**Comment by mzz2017** [comment]
@nadoo About the 2048, some server implementation will respect the document and it is possible to be bigger than 2048.

**Comment by nadoo** [comment]
> @nadoo  I noticed that. But after this PR #302, all sizes are small than 2048 and no any one will exceed.
> 
Interesting，I'll check it later and try to find the reason.

BTW: I use the old code just because I want to avoid unnecessary copies.

**Comment by mzz2017** [comment]
@nadoo Yes, though I don't consider copy because it always costs less, compared with other parts. But I understand your point of view.

**Comment by nadoo** [comment]
According to the [spec](https://www.v2fly.org/en_US/developer/protocols/vmess.html#standard-format): 

> When the transmission is over, the client must send an empty data packet, that is, L = 0 (no encryption) or authentication data length (with encryption) to indicate the end of the transmission.

and the official implementation's [code](https://github.com/v2fly/v2ray-core/blob/054e6679830885c94cc37d27ab2aa96b5b37e019/common/crypto/auth.go#L163-L166):
```Go
if size == uint16(r.auth.Overhead())+padding {
	r.done = true
	return io.EOF
}
```

I'll add the following to our code:
```Go
if int(size) <= r.Overhead() || int(size) > len(p) {
	return 0, io.EOF
}
```

I think that should be OK now.

**Comment by mzz2017** [comment]
@nadoo But I still have a question, does it really affect the exceeded size? I do not understand.

**Comment by nadoo** [comment]
> @nadoo But I still have a question, does it really affect the exceeded size? I do not understand.

Every exceeding chunk will follow a 16 bytes(r.Overhead()) chunk, so if we returned EOF when size=16, we will not get the exceeding chunk.

The exceeding chunk has only 2 bytes length and no payload, I don't know why the server sent this, it's hard to find reason from the source.

**Comment by mzz2017** [comment]
@nadoo Okay, Thanks!

**Pull request merged**
