### PR TITLE
feat: support socks4a

### PR DESCRIPTION
**Pull request by mzz2017**
See https://en.wikipedia.org/wiki/SOCKS#SOCKS4a

### CODE REVIEW

**Comment by mzz2017** [comment]
Do you have a idea of developer community?
I hope that (if is possible) we can talk in a telegram group or other IM to exchange opinions and solve issues conveniently.

**Comment by phantomcraft** [comment]
I tested your commit here, it doesn't work yet:

```
user@localhost:~$ ./go/bin/glider -verbose -listen socks5://127.0.0.1:1080 -forward socks4a://127.0.0.1:9050
2020/12/11 17:55:36 group.go:182: [group] only 1 forwarder found, disable health checking
2020/12/11 17:55:36 server.go:36: [socks5] listening TCP on 127.0.0.1:1080
2020/12/11 17:55:36 server.go:105: [socks5] listening UDP on 127.0.0.1:1080
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44400 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44402 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44404 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44406 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44408 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44410 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44412 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44414 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44416 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44418 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44420 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44422 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44424 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44426 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44428 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44430 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44432 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
2020/12/11 17:55:38 server.go:80: [socks5] 127.0.0.1:44434 <-> www.wikipedia.org:443 via 127.0.0.1:9050, error in dial: [socks4] connection request rejected or failed
```

I also tested the socks4a client of 3proxy (https://github.com/z3APA3A/3proxy) and it works:

```
user@localhost:~$ 3proxy << EOT
log
auth iponly
allow *
parent 1000 socks4+ 127.0.0.1 9050
socks -i127.0.0.1 -p1080
EOT
201211225129.718 1080 00000 - 127.0.0.1:1080 0.0.0.0:0 0 0 0 Accepting connections [54293/2728699648]
201211225152.100 1080 00000 - 127.0.0.1:44138 127.0.0.1:9050 808 4540 1 CONNECT improving.duckduckgo.com:443
201211225203.876 1080 00000 - 127.0.0.1:44122 127.0.0.1:9050 331 1790 1 CONNECT duckduckgo.com:80
201211225206.799 1080 00000 - 127.0.0.1:44142 127.0.0.1:9050 330 570 1 CONNECT wikipedia.org:80
201211225226.085 1080 00000 - 127.0.0.1:44162 127.0.0.1:9050 330 513 1 CONNECT startpage.com:80
201211225228.983 1080 00000 - 127.0.0.1:44166 127.0.0.1:9050 1912 154279 1 CONNECT startpage.com:443
201211225233.838 1080 00000 - 127.0.0.1:44172 127.0.0.1:9050 1019 5408 1 CONNECT www.startpage.com:443
```

I used Tor.

**Comment by mzz2017** [comment]
@phantomcraft Thanks for your test, a potential problem was fixed and you can try it.

**Comment by phantomcraft** [comment]
Not yet. #206

```
user@localhost:~$ go/bin/glider -verbose -listen socks5://127.0.0.1:1080 -forward socks4a://127.0.0.1:9050
2020/12/12 07:13:50 group.go:182: [group] only 1 forwarder found, disable health checking
2020/12/12 07:13:50 server.go:105: [socks5] listening UDP on 127.0.0.1:1080
2020/12/12 07:13:50 server.go:36: [socks5] listening TCP on 127.0.0.1:1080
2020/12/12 07:16:01 server.go:80: [socks5] 127.0.0.1:47116 <-> safebrowsing.googleapis.com:443 via 127.0.0.1:9050, error in dial: [socks4] failed to read greeting from socks4 proxy at 127.0.0.1:9050: EOF
2020/12/12 07:16:06 server.go:80: [socks5] 127.0.0.1:47118 <-> duckduckgo.com:80 via 127.0.0.1:9050, error in dial: [socks4] failed to read greeting from socks4 proxy at 127.0.0.1:9050: EOF
2020/12/12 07:16:28 server.go:80: [socks5] 127.0.0.1:47120 <-> live.thunderbird.net:443 via 127.0.0.1:9050, error in dial: [socks4] failed to read greeting from socks4 proxy at 127.0.0.1:9050: EOF
2020/12/12 07:16:31 server.go:80: [socks5] 127.0.0.1:47122 <-> shavar.services.mozilla.com:443 via 127.0.0.1:9050, error in dial: [socks4] failed to read greeting from socks4 proxy at 127.0.0.1:9050: EOF
2020/12/12 07:17:14 server.go:80: [socks5] 127.0.0.1:47124 <-> api.opensubtitles.org:80 via 127.0.0.1:9050, error in dial: [socks4] failed to read greeting from socks4 proxy at 127.0.0.1:9050: EOF
```

**Comment by phantomcraft** [comment]
socks4a is a socks4 proxy with name resolution, Glider has already support for it:

```
user@localhost:~$ glider -verbose -listen socks5://127.0.0.1:1080 -forward socks4://127.0.0.1:9050
2020/12/12 13:01:40 group.go:182: [group] only 1 forwarder found, disable health checking
2020/12/12 13:01:40 server.go:105: [socks5] listening UDP on 127.0.0.1:1080
2020/12/12 13:01:40 server.go:36: [socks5] listening TCP on 127.0.0.1:1080
2020/12/12 13:01:57 server.go:85: [socks5] 127.0.0.1:48506 <-> safebrowsing.googleapis.com:443 via 127.0.0.1:9050
2020/12/12 13:01:58 server.go:85: [socks5] 127.0.0.1:48512 <-> ocsp.pki.goog:80 via 127.0.0.1:9050
2020/12/12 13:01:59 server.go:85: [socks5] 127.0.0.1:48518 <-> wikipedia.org:80 via 127.0.0.1:9050
2020/12/12 13:02:01 server.go:85: [socks5] 127.0.0.1:48528 <-> shavar.services.mozilla.com:443 via 127.0.0.1:9050
2020/12/12 13:02:01 server.go:85: [socks5] 127.0.0.1:48524 <-> wikipedia.org:443 via 127.0.0.1:9050
2020/12/12 13:02:02 server.go:85: [socks5] 127.0.0.1:48532 <-> ocsp.digicert.com:80 via 127.0.0.1:9050
2020/12/12 13:02:02 server.go:85: [socks5] 127.0.0.1:48534 <-> www.wikipedia.org:443 via 127.0.0.1:9050
2020/12/12 13:02:03 server.go:85: [socks5] 127.0.0.1:48536 <-> tracking-protection.cdn.mozilla.net:443 via 127.0.0.1:9050
2020/12/12 13:02:05 server.go:85: [socks5] 127.0.0.1:48538 <-> upload.wikimedia.org:443 via 127.0.0.1:9050
2020/12/12 13:02:10 server.go:85: [socks5] 127.0.0.1:48540 <-> en.wikipedia.org:443 via 127.0.0.1:9050
2020/12/12 13:02:10 server.go:85: [socks5] 127.0.0.1:48544 <-> en.wikipedia.org:443 via 127.0.0.1:9050
2020/12/12 13:02:20 server.go:85: [socks5] 127.0.0.1:48546 <-> duckduckgo.com:80 via 127.0.0.1:9050
2020/12/12 13:02:22 server.go:85: [socks5] 127.0.0.1:48552 <-> duckduckgo.com:443 via 127.0.0.1:9050
2020/12/12 13:02:23 server.go:85: [socks5] 127.0.0.1:48558 <-> aus2-community.mozilla.org:443 via 127.0.0.1:9050
2020/12/12 13:02:24 server.go:85: [socks5] 127.0.0.1:48564 <-> ocsp.digicert.com:80 via 127.0.0.1:9050
2020/12/12 13:02:25 server.go:85: [socks5] 127.0.0.1:48568 <-> improving.duckduckgo.com:443 via 127.0.0.1:9050
2020/12/12 13:02:25 server.go:85: [socks5] 127.0.0.1:48566 <-> improving.duckduckgo.com:443 via 127.0.0.1:9050
2020/12/12 13:03:24 server.go:80: [socks5] 127.0.0.1:48576 <-> [2a02:c207:2006:2287:0:1:0:1]:9001 via 127.0.0.1:9050, error in dial: [socks4] IPv6 is not supported by socks4
2020/12/12 13:03:25 server.go:80: [socks5] 127.0.0.1:48578 <-> [2a01:4f8:13a:1082::2]:9030 via 127.0.0.1:9050, error in dial: [socks4] IPv6 is not supported by socks4
2020/12/12 13:03:27 server.go:85: [socks5] 127.0.0.1:48580 <-> 62.216.54.29:9001 via 127.0.0.1:9050
```

/\ Names are resolved by the proxy.

**Comment by mzz2017** [comment]
@phantomcraft 

There is a slight difference between socks4 and socks4a: dns resolution happens which sides -- client or server side.

The bug mentioned has been fixed and I'm sorry for my negligent testing.

**Comment by phantomcraft** [comment]
Now it's working:

```
user@localhost:~$ go/bin/glider -verbose -listen socks5://127.0.0.1:1080 -forward socks4a://127.0.0.1:9050
2020/12/13 07:29:49 group.go:182: [group] only 1 forwarder found, disable health checking
2020/12/13 07:29:49 server.go:36: [socks5] listening TCP on 127.0.0.1:1080
2020/12/13 07:29:49 server.go:105: [socks5] listening UDP on 127.0.0.1:1080
2020/12/13 07:29:52 server.go:85: [socks5] 127.0.0.1:50446 <-> duckduckgo.com:443 via 127.0.0.1:9050
2020/12/13 07:29:54 server.go:85: [socks5] 127.0.0.1:50448 <-> improving.duckduckgo.com:443 via 127.0.0.1:9050
2020/12/13 07:30:04 server.go:85: [socks5] 127.0.0.1:50450 <-> wikipedia.org:443 via 127.0.0.1:9050
2020/12/13 07:30:06 server.go:85: [socks5] 127.0.0.1:50452 <-> www.wikipedia.org:443 via 127.0.0.1:9050
2020/12/13 07:30:07 server.go:85: [socks5] 127.0.0.1:50454 <-> upload.wikimedia.org:443 via 127.0.0.1:9050
2020/12/13 07:30:11 server.go:85: [socks5] 127.0.0.1:50456 <-> 46.4.88.92:9002 via 127.0.0.1:9050
2020/12/13 07:30:12 server.go:85: [socks5] 127.0.0.1:50458 <-> 51.255.150.177:443 via 127.0.0.1:9050
2020/12/13 07:30:13 server.go:85: [socks5] 127.0.0.1:50460 <-> en.wikipedia.org:443 via 127.0.0.1:9050
2020/12/13 07:30:13 server.go:85: [socks5] 127.0.0.1:50462 <-> 51.15.4.202:9001 via 127.0.0.1:9050
2020/12/13 07:30:25 server.go:85: [socks5] 127.0.0.1:50482 <-> startpage.com:80 via 127.0.0.1:9050
2020/12/13 07:30:26 server.go:85: [socks5] 127.0.0.1:50484 <-> startpage.com:443 via 127.0.0.1:9050
2020/12/13 07:30:29 server.go:85: [socks5] 127.0.0.1:50486 <-> www.startpage.com:443 via 127.0.0.1:9050
```

I tested the socks4:// of Glider and analyzed the traffic with Wireshark, I didn't see any DNS request on my side, does Glider makes DNS resolution in TCP mode through thee socks4:// tunnel?

**Comment by mzz2017** [comment]
https://github.com/nadoo/glider/blob/42c15b9262e16c1832f10cd63c4c19e683840042/proxy/socks4/socks4.go#L126

The dns resolution can be found here.

**Comment by phantomcraft** [comment]
/\ Sorry, I was wrong.

I thought that Glider was using its internal resolver (8.8.8.8:53) to resolve names in the socks4 connections, it uses the system DNS, I checked my loopback interface in Wireshark and could see the DNS queries being made.

I also checked your socks4a:// mode and isn't leaking anything, DNS resolutions are made in the proxy tunnel. Your implementation works.

I'm waiting for @nadoo for merging your commit in the master/dev.

**Comment by nadoo** [comment]
Hi @mzz2017 @phantomcraft , thanks for your work, I got busy these days and I'll merge it soon.

**Pull request merged**
