### PR TITLE
feat: support routingA

### PR DESCRIPTION
**Pull request by mzz2017**
### Usage Example

**Directory Structure**

```
.
├── glider.conf
├── routingA
└── rules.d
    └── youtube.rule
```

**glider.conf**
```
verbose=True
listen=mixed://127.0.0.1:10888
forward=ss://AEAD_AES_128_GCM:password@103.121.*.*:18080
rules-dir=rules.d
routingA=routingA
```

**youtube.rule**
```
forward=ws://104.194.*.*:8080/,vmess://3b446***-2a7e********-62f********42@?alterID=1
```

**routingA**
```
default:proxy
domain(ip111.cn,youtube.com)->youtube
domain(baidu.com)->reject
```

**Result**

Access to `ip111.cn` and `youtube.com` (and their sub-domain) will use the forwarding defined in `youtube.rule`.

Access to `baidu.com` (and its sub-domain) will be rejected.

Other access use forwarding group defined in main config.

### Format

Slightly differrent from what in v2rayA.

```
# preset outbounds are proxy (main group), direct and reject.
# every filename in rule.d will be available as an outbound group.
default:proxy

# domain rules
domain(ip111.cn,youtube.com)->youtube
domain(baidu.com)->reject

# target ip rules
tip(192.168.0.0/16)->direct

# target port rules
tport(8080)->direct

# network
network(udp)->direct

# and rules
network(tcp) && domain(223.5.5.5) -> youtube
tip(192.168.0.15) && tport(1080) && network(tcp)-> reject
```

### CODE REVIEW

**Comment by mzz2017** [comment]
Related #201

**Comment by mzz2017** [comment]
Testing is inadequate, and if you are interested in it, more tests I will do.

**Comment by nadoo** [comment]
Thanks! I'll study it in this weekend.

**Comment by qqqqqqrrrrhh123a** [comment]
https://github.com/nadoo/glider/issues/270 ,help me

**Pull request closed without merging**
